/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddProduct: typeof import('./src/components/AddProduct.vue')['default']
    AddProductModal: typeof import('./src/components/AddProductModal.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ProductDetailsModal: typeof import('./src/components/ProductDetailsModal.vue')['default']
    ProductList: typeof import('./src/components/ProductList.vue')['default']
    Welcome: typeof import('./src/components/Welcome.vue')['default']
  }
}
