/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddProductModal: typeof import('./src/components/AddProductModal.vue')['default']
    EditProductModal: typeof import('./src/components/EditProductModal.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    ProductDetailsModal: typeof import('./src/components/ProductDetailsModal.vue')['default']
    ProductList: typeof import('./src/components/ProductList.vue')['default']
    ProductMgmt: typeof import('./src/components/ProductMgmt.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Welcome: typeof import('./src/components/Welcome.vue')['default']
  }
}
